default: &default
  adapter: mysql2
  encoding: utf8
  host: db
  username: root
  password: group17
  # username: admin
  # password: admin

development:
  <<: *default
  database: docker_dev

test:
  <<: *default
  database: docker_test

